spring.datasource.url=jdbc:mysql://tienda-zapa-pruebaadsadadad.j.aivencloud.com:16424/tienda_zapas?ssl-mode=REQUIRED

spring.datasource.username=avnadmin
spring.datasource.password=AVNS_FWtu3EbUrydWtvcbRLl

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}
